curl --location 'https://api.aliprice.com/v2/Item/searchImageV2' \
--header 'Host: api.aliprice.com' \
--header 'version: 7.0.6' \
--header 'language: en' \
--header 'device: android' \
--header 'whichapp: Android_Assistant' \
--header 'currency: IDR' \
--header 'content-type: application/json; charset=utf-8' \
--header 'accept-encoding: gzip' \
--header 'cookie: PHPSESSID=6ie13j44ccpblpqaansisd6vhl; country_code=ID; cookie_id=dZnk9gupWZEiw61b1716903339; language=english; cookie_id=euz9rLeVZ5YayISA1716676053; country_code=ID; language=english' \
--header 'user-agent: okhttp/3.12.0' \
--data '{"data":"{\"website\":\"1688_lite2\",\"size\":20,\"uploadKey\":\"1717240552-895.png\",\"phash\":\"vlZmhy/8cio7bk7/gvWcpvQDDPpt4+0sR6W6dEo36alfkM0iC/MYuquiObpzxufL/7gaOvs4AHBsCT2oM/PjcA\\u003d\\u003d\",\"cateid\":\"\",\"taobao_cateid\":\"\",\"page\":2,\"1688_cateid\":\"\"}"}'
